In [1]:
%load_ext autoreload
%autoreload 2
import sys
import numpy as np
sys.path.append("..")
from data_loader import PuncDataset
from train_truncated_bptt import get_one_batch_data

In [2]:
tr_dataset = PuncDataset('train', 'vocab', 'punc_vocab')
print(len(tr_dataset))

300


In [7]:
batch_size = 3
feats_utt = [np.array([])] * batch_size  # every element is numpy ndarray
targets_utt = [np.array([])] * batch_size
new_utt_flags = [0] * batch_size

for i in range(3):
    idx = 0
    inputs, targets, new_utt_flags, done = get_one_batch_data(tr_dataset, feats_utt, targets_utt, new_utt_flags, batch_size, 20, idx)
    print(inputs)
    print(targets)
    print(new_utt_flags)
    print(done)

[[  0.   5.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [ 55.   0.   0.]
 [  0.  15.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [ 55.   0.   0.]
 [  0.   0.   5.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  2.  15.  10.]
 [  0.   0.   0.]
 [  0.  37.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.  96.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 2.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
[1, 1, 1]
False
[[  0.   0.   0.]
 [ 99.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   2.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.  25.  12.]
 [  0.   0.  96.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   8.   0.]
 [  0.   0.   0.

[[  0.   5.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [ 55.   0.   0.]
 [  0.  15.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [ 55.   0.   0.]
 [  0.   0.   5.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  2.  15.  10.]
 [  0.   0.   0.]
 [  0.  37.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.  96.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 2.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
[1, 1, 1]
False
